version: 1.0.0

Paths:
    imageDir: "./imgs"

ScaleFactor: 0.7

Preprocessing:
    GaussianBlur:
        kernelSize: 3

SIFT:
    nFeatures: 0
    nOctaveLayers: 3
    contrastThreshold: 0.04 #0.03
    edgeThreshold: 10 #20
    sigma: 1.6 #1.4

FeatureMatching:
    lowes_const: 0.75 #0.75
    RANSAC_THRESH: 5.0 #8.0
    MIN_MATCH_COUNT: 10
