version: 1.0.0

Paths:
    mode: 1
    imageDir: "E:/Github/EECE7150/Assignment3/29images"
    # imageDir: "./imgs/6Images/"

ScaleFactor: 0.3

Preprocessing:
    GaussianBlur:
        kernelSize: 3

SIFT:
    nFeatures: 0
    nOctaveLayers: 3
    contrastThreshold: 0.03 #0.03
    edgeThreshold: 20 #20
    sigma: 1.4 #1.4

FeatureMatching:
    lowes_const: 0.75 #0.75
    RANSAC_THRESH: 3.0 #8.0
    MIN_MATCH_COUNT: 10
